---
- hosts: all
  vars:
    ip_master: 192.168.63.10
    ip_data: 192.168.63.11
    ip_monitoring: 192.168.63.20
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "{{ ip_master }} node-master.example.com node-master"
        - "{{ ip_data }} node-data.example.com node-data"
        - "{{ ip_monitoring }} monitoring.example.com monitoring"

    - name: Garantindo usuário
      user:
        name: sysadmin
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: rsa

    - name: Garantindo poder de super usuário
      lineinfile:
        path: /etc/sudoers.d/sysadmin
        line: sysadmin ALL=(ALL) NOPASSWD:ALL
        create: yes

    - name: Configurando Private Key
      copy:
        src: /vagrant/files/keys/id_rsa
        dest: /home/sysadmin/.ssh/id_rsa
        mode: '0600'

    - name: Configurando Public Key
      copy:
        src: /vagrant/files/keys/id_rsa.pub
        dest: /home/sysadmin/.ssh/id_rsa.pub
        mode: '0644'

    - name: Configurando authorized keys do usuário
      ansible.posix.authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', '/vagrant/files/keys/id_rsa.pub') }}"

    - name: Garantindo pacotes essenciais
      package:
        name:
          - apt-transport-https
          - curl
          - vim
          - telnet

    - name: Garantindo chave do repositório
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Garantindo repositório
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        filename: elastic-8
