---
- hosts: all
  vars:
    ip_master: 192.168.63.10
    ip_data: 192.168.63.11
    ip_monitoring: 192.168.63.20
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "{{ ip_master }} node-master.example.com node-master"
        - "{{ ip_data }} node-data.example.com node-data"
        - "{{ ip_monitoring }} monitoring.example.com monitoring"

    - name: Garantindo usu치rio
      user:
        name: sysadmin
        shell: /bin/bash

    - name: Garantindo poder de super usu치rio
      lineinfile:
        path: /etc/sudoers.d/sysadmin
        line: sysadmin ALL=(ALL) NOPASSWD:ALL
        create: yes

    - name: Garantindo pacotes essenciais
      package:
        name:
          - apt-transport-https
          - curl
          - vim
          - telnet

    - name: Garantindo chave do reposit칩rio
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Garantindo reposit칩rio
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        filename: elastic-8
