version: '3'

services:
  4coffee_app:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile
    command: gunicorn --bind  0.0.0.0:5001 wsgi:app --timeout 0
    expose:
      - 5001
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - 4coffee_app
